services:
  app:
    image: node:20
    container_name: sensor-app
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DB_URI=mongodb://admin:admin@mongo:27017/sensor_database?authSource=admin
      - PORT=4000
    command: npm run start:dev
    ports:
      - '4000:4000'
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: sensor-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
